<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22956" started-at="2015-01-19T09:53:04Z" finished-at="2015-01-19T09:53:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22956" started-at="2015-01-19T09:53:04Z" finished-at="2015-01-19T09:53:27Z">
      <class name="com.ptl.testcases.doc244duplicateemail">
        <test-method status="PASS" signature="init()[pri:0, instance:com.ptl.testcases.doc244duplicateemail@4917b9b2]" name="init" is-config="true" duration-ms="4247" started-at="2015-01-19T15:22:59Z" finished-at="2015-01-19T15:23:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="RegNewExpTest(java.util.Hashtable)[pri:0, instance:com.ptl.testcases.doc244duplicateemail@4917b9b2]" name="RegNewExpTest" duration-ms="13282" started-at="2015-01-19T15:23:04Z" data-provider="getExporterRegData" finished-at="2015-01-19T15:23:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{COO Mobile=0712234556, Contact Person=Suranga Disasekara, Official Address=23, New Kandy Rd, Mabima, Username=docdeptadmin, Fax=0112255324, Runmode=Yes, Tel=0112255432, Company Name=Laugfs PLC, Password=1qaz2wsx@, COO Email=surangaotheremail@yahoo.com, COO Name=Saranga Kumara, Business RegNo=LSA27774, Contact Email=surangaotheremail@yahoo.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exporter Registration Fail expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exporter Registration Fail expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ptl.DOC.pages.ExporterRegPage.doRegisterNewExporter(ExporterRegPage.java:82)
	at com.ptl.testcases.doc244duplicateemail.RegNewExpTest(doc244duplicateemail.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegNewExpTest -->
        <test-method status="FAIL" signature="RegNewExpTest(java.util.Hashtable)[pri:0, instance:com.ptl.testcases.doc244duplicateemail@4917b9b2]" name="RegNewExpTest" duration-ms="9643" started-at="2015-01-19T15:23:17Z" data-provider="getExporterRegData" finished-at="2015-01-19T15:23:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{COO Mobile=0723994254, Contact Person=Harry Jaawreerten, Official Address=107, New kendy rd, Mabaso, Username=docdeptadmin, Fax=0192699459, Runmode=yes, Tel=0112999922, Company Name=VPELintar, Password=1qaz2wsx@, COO Email=hay2j29@gmail.com, COO Name=Harry erereeerria, Business RegNo=LSA95334, Contact Email=hrr9332@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exporter Registration Fail expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exporter Registration Fail expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ptl.DOC.pages.ExporterRegPage.doRegisterNewExporter(ExporterRegPage.java:82)
	at com.ptl.testcases.doc244duplicateemail.RegNewExpTest(doc244duplicateemail.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegNewExpTest -->
      </class> <!-- com.ptl.testcases.doc244duplicateemail -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
